### ISSUE TITLE
user panel button doesn't refresh after pressing keybind or pressing button in status picker

### ISSUE THREAD

**Issue by TheMooskyFish** [Tharki-God/ReGameActivityToggle#3]
title says everything

**Comment by yofukashino** [comment]
> title says everything
are you on the latest version because using both the status picker and key bind the user panel button refreshes for me

**Comment by TheMooskyFish** [comment]
i using latest version and still not refreshing UNLESS i move cursor to user panel area

**Comment by yofukashino** [comment]
![regameactivity](https://user-images.githubusercontent.com/73281112/222154316-408d37f8-652d-4523-81b3-9cc592522546.gif)
as you can see it updates for me
and no i am not gonna do that in granny mode again

**Comment by TheMooskyFish** [comment]
https://user-images.githubusercontent.com/32228338/222189460-79a70200-357c-40c9-9297-de2fee91ecbb.mp4

legit updated to 0.9.9 version and still same thing

**Comment by yofukashino** [comment]
> https://user-images.githubusercontent.com/32228338/222189460-79a70200-357c-40c9-9297-de2fee91ecbb.mp4
> 
> legit updated to 0.9.9 version and still same thing

Either I am blessed or you are cursed

**Comment by TheMooskyFish** [comment]
tested on other computer
fresh replugged and having same issue there

**Comment by yofukashino** [comment]
Can't replicate so can't fix

**Comment by TheMooskyFish** [comment]
can't replicate even with fresh replugged without plugins?

**Comment by yofukashino** [comment]
> can't replicate even with fresh replugged without plugins?

Haven't tried that yet. Imma try that soon

**Comment by yofukashino** [comment]
> > can't replicate even with fresh replugged without plugins?
> 
> Haven't tried that yet. Imma try that soon

well on fresh install of replugged with openasar and it still works as intended for me

**Comment by TheMooskyFish** [comment]
very weird

**Comment by TheMooskyFish** [comment]
ok i guess i going close this issue cuz legit can't find cause of issue (also button does refresh when i move to other server or channel)

EDIT: tested in linux vm and same thing

**Comment by yofukashino** [comment]
Windows superior

**Comment by TheMooskyFish** [comment]
i agree
