### ISSUE TITLE
If you disable the user panel button, all the buttons are aligned to the left

### ISSUE THREAD

**Issue by ghost** [Tharki-God/ReGameActivityToggle#4]
Disabling the user panel button makes all the buttons aligned to the left:
![image](https://user-images.githubusercontent.com/52091217/225509172-a6d9b3b2-6f14-4c7f-8888-7d030c9503cf.png)

**Comment by yofukashino** [comment]
Seems like a problem with your css

**Comment by yofukashino** [comment]
Imma close this issue due to lack of response

**Comment by yofukashino** [comment]
> Disabling the user panel button makes all the buttons aligned to the left: ![image](https://user-images.githubusercontent.com/52091217/225509172-a6d9b3b2-6f14-4c7f-8888-7d030c9503cf.png)

found what was the issue and fixed in latest update. update your plugin to fix it pls
