### ISSUE TITLE
User panel button doesn't work when play audio is active

### ISSUE THREAD

**Issue by Cyenia** [Tharki-God/ReGameActivityToggle#5]
![image](https://github.com/Tharki-God/ReGameActivityToggle/assets/35280763/0e0366d1-1102-4b65-8ccb-bd14928ff9c5)

<details>
<summary>Console Log</summary>
<pre>
717531d4d2aa46ed5d3f.js:1 Uncaught TypeError: G.playSound is not a function
    at g (renderer.js?t=1700326854238:1:2912)
    at onClick (renderer.js?t=1700326854238:1:8143)
    at onClick (54048cbca82971e90db8.js:1:380586)
    at Object.eN (717531d4d2aa46ed5d3f.js:1:751176)
    at eB (717531d4d2aa46ed5d3f.js:1:751330)
    at 717531d4d2aa46ed5d3f.js:1:769639
    at re (717531d4d2aa46ed5d3f.js:1:769738)
    at rt (717531d4d2aa46ed5d3f.js:1:770152)
    at 717531d4d2aa46ed5d3f.js:1:775614
    at sE (717531d4d2aa46ed5d3f.js:1:832671)
g @ renderer.js?t=1700326854238:1
onClick @ renderer.js?t=1700326854238:1
onClick @ 54048cbca82971e90db8.js:1
eN @ 717531d4d2aa46ed5d3f.js:1
eB @ 717531d4d2aa46ed5d3f.js:1
(anonymous) @ 717531d4d2aa46ed5d3f.js:1
re @ 717531d4d2aa46ed5d3f.js:1
rt @ 717531d4d2aa46ed5d3f.js:1
(anonymous) @ 717531d4d2aa46ed5d3f.js:1
sE @ 717531d4d2aa46ed5d3f.js:1
eC @ 717531d4d2aa46ed5d3f.js:1
rs @ 717531d4d2aa46ed5d3f.js:1
tN @ 717531d4d2aa46ed5d3f.js:1
tF @ 717531d4d2aa46ed5d3f.js:1
</pre>
</details>

**Comment by yofukashino** [comment]
known. will fix when after I recover.

**Comment by yofukashino** [comment]
took my sweet time to recover... (i forgot to commit)
