### ISSUE TITLE
Button isn't working

### ISSUE THREAD

**Issue by Czekoloczek** [Tharki-God/ReGameActivityToggle#7]
![image](https://github.com/YofukashiNo/ReGameActivityToggle/assets/76474182/0f669480-8cbd-4c15-94bb-4c6d16a8b383)
Clicking the Button causes this error to appear in the console
(also nothing is happening when you press the button)

**Comment by Czekoloczek** [comment]
The button works normally if i disable playing the sound in the plugin settings

**Comment by yofukashino** [comment]
which version?

**Comment by Czekoloczek** [comment]
Idk what version do you need so
Discord:
canary 290661 (216a0e6) Host 1.0.341 x64 (47493) Windows 11 64-bit (10.0.22631)
Replugged:
v4.7.9
Plugin:
v1.1.3

**Comment by yofukashino** [comment]
well latest version for plugin is 1.2.8 wait. its fixed but cant be updated onto store because of https://github.com/YofukashiNo/ReGameActivityToggle/issues/6
